baseURL = "https://stewartbiology.com/"
locale = "en-US"
title = "Jonathan Stewart"
theme = "ananke"

enableRobotsTXT = true

[params]
description = "Environmental toxicology PhD student studying how contaminants affect human and environmental health."
body_classes = "stewart-home"
custom_css = ["css/stewart-home.css"]

[[menus.main]]
name = "Home"
url = "/"
weight = 10

[[menus.main]]
name = "CV"
url = "https://drive.google.com/file/d/1xZok07WyOP-T-Nb8HH4jQI-ZROvsTPc-/view?usp=share_link"
weight = 20

[[menus.main]]
name = "Resume"
url = "https://drive.google.com/file/d/1bpDX37iYolYQsll5DwtDu7P2OUzlVteA/view?usp=sharing"
weight = 30

[[menus.main]]
name = "Presentations"
url = "/presentations/"
weight = 40

[[menus.main]]
name = "Projects"
identifier = "projects"
url = "/projects/"
weight = 50

[[menus.main]]
name = "AFFF alternatives"
parent = "projects"
url = "/projects/afff-alternatives/"
weight = 10

[[menus.main]]
name = "Publications"
url = "/publications/"
weight = 60
